algoritmo "APLICANDO_DESCONTO"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Leonardo Lemos


var
   Valor, QuinzePorcento : real

inicio
      Escreval("=============== APLICANDO O DESCONTO =============")
      Escreval (" ")
      Escreval ("QUAL VALOR:")
      Leia (Valor)
      //atribuição dos valores
      QuinzePorcento <-(Valor * 0.15)
      //condicionais
      Escreval ("Com o desconto ficou:", QuinzePorcento)

fimalgoritmo