Algoritmo "OLA MUNDO 20 VEZES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Lemos
// Descrição   : Digitar Olá Mundo 20 vezes
// Autor(a)    : Caio Menezes Brito
Var
// Seção de Declarações das variáveis
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para contador de 1 ate 20 faca
        Escreval ("Olá Mundo")
   FimPara
   

Fimalgoritmo