Algoritmo "1 a 200 IMPARES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Lemos
// Descrição   : 1 a 199 impares
// Autor(a)    : Caio Menezes Brito
Var
// Seção de Declarações das variáveis
   contador, Num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Num <- -1
   Para contador de 1 ate 100 faca
        Num <- Num + 2
        Escreval (Num)
   FimPara
   

Fimalgoritmo