Algoritmo "20 VEZES - OLA MUNDO"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Leonardo Lemos
// Descrição   : 20 vezes olá mundo
// Autor(a)    : Caio Menezes Brito
Var
// Seção de Declarações das variáveis
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para contador de 1 ate 20 faca
        Escreval ("OLÁ MUNDO")
   FimPara
   

Fimalgoritmo